// for users
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_LOCAL_STORAGE = "VERIFY_LOCAL_STORAGE";
export const UPDATE_USER = "UPDATE_USER";

// for posts
export const GET_ALL_POST = "GET_ALL_POST";
export const GET_ONLY_USER_POST = "GET_ONLY_USER_POST";
export const GET_LIKE_UNLIKE_POST = "GET_LIKE_UNLIKE_POST"
export const GET_COMMENT_POST = "GET_COMMENT_POST";
