// for users

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const VERIFY_SUCCESS = "VERIFY_SUCCESS";

export const VERIFY_LOCAL_STORAGE = "VERIFY_LOCAL_STORAGE";