// for users
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_LOCAL_STORAGE = "VERIFY_LOCAL_STORAGE";
export const UPDATE_USER = "UPDATE_USER";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_FOLLOWER = "GET_USER_FOLLOWER";
export const GET_USER_UNFOLLOWER = "GET_USER_UNFOLLOWER";
export const GET_All_USER = "GET_All_USER";
export const DELETE_USER = "DELETE_USER";

// for posts
export const GET_ALL_POST = "GET_ALL_POST";
export const CREATE_NEW_POST = "CREATE_NEW_POST";
export const GET_ONLY_USER_POST = "GET_ONLY_USER_POST";
export const GET_LIKE_UNLIKE_POST = "GET_LIKE_UNLIKE_POST"
export const GET_COMMENT_POST = "GET_COMMENT_POST";
export const GET_DELETE_POST = "GET_DELETE_POST";
